const BAGS = [
  {
    id: 'cacao',
    num: '01',
    name: 'Cacao',
    altNoun: 'bag',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/cacao.jpg', 'assets/cacao.jpg', 'assets/cacao.jpg'],
    desc: 'A rounded hobo with a single wide handle that sits close to the shoulder. The stitch is left dense and irregular so the surface catches light differently from every angle.',
    specs: [
      ['Material', '100% cotton ribbon yarn'],
      ['Stitch', 'Bobble, left dense and irregular'],
      ['Silhouette', 'Rounded hobo'],
      ['Handle', 'Single wide shoulder handle'],
      ['Hardware', 'Engraved brass plaque'],
    ],
  },
  {
    id: 'foret',
    num: '02',
    name: 'Forêt',
    altNoun: 'bag',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/foret.jpg', 'assets/foret.jpg', 'assets/foret.jpg'],
    desc: 'Two yarns worked together, so the color shifts as the bag moves. The most textural piece in the collection and the one that reads as handmade from across a room.',
    specs: [
      ['Material', 'Two cotton ribbon yarns, worked together'],
      ['Stitch', 'Two-tone bobble'],
      ['Color', 'Forest green and cream'],
      ['Hardware', 'Engraved brass plaque'],
    ],
  },
  {
    id: 'rubis',
    num: '03',
    name: 'Rubis',
    altNoun: 'bag',
    variant: 'rubis',
    imgW: 1536,
    imgH: 2048,
    images: ['assets/rubis.jpg', 'assets/rubis.jpg', 'assets/rubis.jpg'],
    desc: 'A soft shoulder bag with a double strap and pearls set into the stitch by hand, one at a time, in no fixed pattern.',
    specs: [
      ['Material', '100% cotton ribbon yarn'],
      ['Stitch', 'Single crochet with pearls set in'],
      ['Detailing', 'Freshwater-look pearls, placed by hand'],
      ['Handle', 'Double shoulder strap'],
      ['Hardware', 'Engraved brass plaque'],
    ],
  },
  {
    id: 'nuage',
    num: '04',
    name: 'Nuage',
    altNoun: 'clutch',
    variant: 'nuage',
    imgW: 2048,
    imgH: 1536,
    images: ['assets/nuage.jpg', 'assets/nuage.jpg', 'assets/nuage.jpg'],
    desc: 'The quietest piece. A structured pillow clutch with a slot handle and an even, tight stitch. Made for evenings when the bag should not be the loudest thing in the room.',
    specs: [
      ['Material', '100% cotton ribbon yarn'],
      ['Stitch', 'Even, tight single crochet'],
      ['Silhouette', 'Structured pillow clutch'],
      ['Handle', 'Integrated slot'],
      ['Hardware', 'Engraved brass plaque'],
    ],
  },
  {
    id: 'maree',
    num: '05',
    name: 'Marée',
    altNoun: 'bag',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/maree.jpg', 'assets/maree.jpg', 'assets/maree.jpg'],
    desc: 'The most worked piece we make. Roughly forty charms and pearls, each one attached individually into the stitch.',
    specs: [
      ['Material', '100% cotton ribbon yarn'],
      ['Stitch', 'Dense single crochet, structured body'],
      ['Dimensions', '34 × 26 × 11 cm'],
      ['Handle', 'Integrated cut-out'],
      ['Detailing', 'Gold-tone charms, glass pearls'],
      ['Hardware', 'Engraved brass plaque'],
    ],
  },
];
