const BAGS = [
  {
    id: 'cacao',
    num: '01',
    name: 'Olea',
    altNoun: 'torba',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/cacao.jpg', 'assets/cacao.jpg', 'assets/cacao.jpg'],
    desc: 'Zaobljena hobo torba sa jednom širokom ručkom koja naleže blizu ramena. Vez je ostavljen gust i nepravilan, tako da površina hvata svetlost drugačije iz svakog ugla.',
    specs: [
      ['Materijal', '100% pamučna traka'],
      ['Vez', 'Bobl bod, gust i nepravilan'],
      ['Silueta', 'Zaobljena hobo torba'],
      ['Ručka', 'Jedna široka ručka za rame'],
      ['Detalji', 'Gravirana mesingana pločica'],
    ],
  },
  {
    id: 'foret',
    num: '02',
    name: 'Forêt',
    altNoun: 'torba',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/foret.jpg', 'assets/foret.jpg', 'assets/foret.jpg'],
    desc: 'Dve pređe upletene zajedno, tako da se boja menja kako se torba pomera. Najteksturisaniji komad u kolekciji, onaj koji se prepoznaje kao ručna izrada i s druge strane sobe.',
    specs: [
      ['Materijal', 'Dve pamučne trake, upletene zajedno'],
      ['Vez', 'Dvobojni bobl bod'],
      ['Boja', 'Šumsko zelena i krem'],
      ['Detalji', 'Gravirana mesingana pločica'],
    ],
  },
  {
    id: 'rubis',
    num: '03',
    name: 'Rubis',
    altNoun: 'torba',
    variant: 'rubis',
    imgW: 1536,
    imgH: 2048,
    images: ['assets/rubis.jpg', 'assets/rubis.jpg', 'assets/rubis.jpg'],
    desc: 'Mekana torba na rame sa dvostrukom trakom i biserima ukomponovanim u vez ručno, jedan po jedan, bez fiksnog rasporeda.',
    specs: [
      ['Materijal', '100% pamučna traka'],
      ['Vez', 'Jednostruki bod sa ukomponovanim biserima'],
      ['Detalji', 'Biseri nalik rečnim, postavljeni ručno'],
      ['Ručka', 'Dvostruka traka za rame'],
      ['Kopča/okov', 'Gravirana mesingana pločica'],
    ],
  },
  {
    id: 'nuage',
    num: '04',
    name: 'Nuage',
    altNoun: 'klač torbica',
    variant: 'nuage',
    imgW: 2048,
    imgH: 1536,
    images: ['assets/nuage.jpg', 'assets/nuage.jpg', 'assets/nuage.jpg'],
    desc: 'Najmirniji komad. Strukturirana klač torbica u obliku jastuka sa prorezom za ručku i ravnomernim, čvrstim vezom. Napravljena za večeri kada torba ne treba da bude najupadljivija stvar u prostoriji.',
    specs: [
      ['Materijal', '100% pamučna traka'],
      ['Vez', 'Ravnomeran, čvrst jednostruki bod'],
      ['Silueta', 'Strukturirana klač torbica u obliku jastuka'],
      ['Ručka', 'Ugrađeni prorez'],
      ['Detalji', 'Gravirana mesingana pločica'],
    ],
  },
  {
    id: 'maree',
    num: '05',
    name: 'Marée',
    altNoun: 'torba',
    variant: null,
    imgW: 1536,
    imgH: 2048,
    images: ['assets/maree.jpg', 'assets/maree.jpg', 'assets/maree.jpg'],
    desc: 'Najzahtevniji komad koji izrađujemo. Oko četrdeset privezaka i bisera, svaki pojedinačno ukomponovan u vez.',
    specs: [
      ['Materijal', '100% pamučna traka'],
      ['Vez', 'Gust jednostruki bod, strukturirano telo'],
      ['Dimenzije', '34 × 26 × 11 cm'],
      ['Ručka', 'Ugrađeni izrez'],
      ['Detalji', 'Privesci u zlatnom tonu, stakleni biseri'],
      ['Kopča/okov', 'Gravirana mesingana pločica'],
    ],
  },
];
